# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/options.ui'
#
# Created: Thu Aug 22 23:19:47 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_OptionsDialog(object):
    def setupUi(self, OptionsDialog):
        OptionsDialog.setObjectName("OptionsDialog")
        OptionsDialog.setWindowModality(QtCore.Qt.NonModal)
        OptionsDialog.resize(748, 605)
        OptionsDialog.setModal(True)
        self.verticalLayoutWidget_2 = QtGui.QWidget(OptionsDialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 741, 601))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.verticalLayoutWidget_2)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 671, 520))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lay = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.lay.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.lay.setContentsMargins(0, 0, -1, -1)
        self.lay.setObjectName("lay")
        self.CompanyTableWidget = QtGui.QTableWidget(self.verticalLayoutWidget)
        self.CompanyTableWidget.setAlternatingRowColors(True)
        self.CompanyTableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.CompanyTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.CompanyTableWidget.setRowCount(1)
        self.CompanyTableWidget.setColumnCount(2)
        self.CompanyTableWidget.setObjectName("CompanyTableWidget")
        self.CompanyTableWidget.setColumnCount(2)
        self.CompanyTableWidget.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.CompanyTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.CompanyTableWidget.setHorizontalHeaderItem(1, item)
        self.CompanyTableWidget.horizontalHeader().setDefaultSectionSize(300)
        self.lay.addWidget(self.CompanyTableWidget)
        self.AddButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.AddButton.setFlat(False)
        self.AddButton.setObjectName("AddButton")
        self.lay.addWidget(self.AddButton)
        self.DeleteButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.DeleteButton.setObjectName("DeleteButton")
        self.lay.addWidget(self.DeleteButton)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 671, 501))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.PovTableWidget = QtGui.QTableWidget(self.verticalLayoutWidget_3)
        self.PovTableWidget.setAlternatingRowColors(True)
        self.PovTableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.PovTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.PovTableWidget.setRowCount(2)
        self.PovTableWidget.setColumnCount(2)
        self.PovTableWidget.setObjectName("PovTableWidget")
        self.PovTableWidget.setColumnCount(2)
        self.PovTableWidget.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.PovTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.PovTableWidget.setHorizontalHeaderItem(1, item)
        self.PovTableWidget.horizontalHeader().setDefaultSectionSize(300)
        self.verticalLayout_3.addWidget(self.PovTableWidget)
        self.AddPovButton = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.AddPovButton.setObjectName("AddPovButton")
        self.verticalLayout_3.addWidget(self.AddPovButton)
        self.DeletePovButton = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.DeletePovButton.setObjectName("DeletePovButton")
        self.verticalLayout_3.addWidget(self.DeletePovButton)
        self.tabWidget.addTab(self.tab, "")
        self.widget = QtGui.QWidget()
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.widget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(2, 3, 731, 521))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.PTableWidget = QtGui.QTableWidget(self.verticalLayoutWidget_4)
        self.PTableWidget.setAlternatingRowColors(True)
        self.PTableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.PTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.PTableWidget.setRowCount(2)
        self.PTableWidget.setColumnCount(1)
        self.PTableWidget.setObjectName("PTableWidget")
        self.PTableWidget.setColumnCount(1)
        self.PTableWidget.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.PTableWidget.setHorizontalHeaderItem(0, item)
        self.PTableWidget.horizontalHeader().setDefaultSectionSize(400)
        self.verticalLayout_4.addWidget(self.PTableWidget)
        self.PAddButton = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.PAddButton.setObjectName("PAddButton")
        self.verticalLayout_4.addWidget(self.PAddButton)
        self.PDeleteButton = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.PDeleteButton.setObjectName("PDeleteButton")
        self.verticalLayout_4.addWidget(self.PDeleteButton)
        self.line = QtGui.QFrame(self.verticalLayoutWidget_4)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.PMITableWidget = QtGui.QTableWidget(self.verticalLayoutWidget_4)
        self.PMITableWidget.setObjectName("PMITableWidget")
        self.PMITableWidget.setColumnCount(4)
        self.PMITableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.PMITableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.PMITableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.PMITableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.PMITableWidget.setHorizontalHeaderItem(3, item)
        self.PMITableWidget.horizontalHeader().setDefaultSectionSize(180)
        self.verticalLayout_4.addWidget(self.PMITableWidget)
        self.PMIAddButton = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.PMIAddButton.setObjectName("PMIAddButton")
        self.verticalLayout_4.addWidget(self.PMIAddButton)
        self.PMIDeleteButton = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.PMIDeleteButton.setObjectName("PMIDeleteButton")
        self.verticalLayout_4.addWidget(self.PMIDeleteButton)
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.tab_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 671, 501))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tTableWidget = QtGui.QTableWidget(self.verticalLayoutWidget_5)
        self.tTableWidget.setAlternatingRowColors(True)
        self.tTableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tTableWidget.setRowCount(2)
        self.tTableWidget.setColumnCount(1)
        self.tTableWidget.setObjectName("tTableWidget")
        self.tTableWidget.setColumnCount(1)
        self.tTableWidget.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tTableWidget.setHorizontalHeaderItem(0, item)
        self.tTableWidget.horizontalHeader().setDefaultSectionSize(400)
        self.verticalLayout_5.addWidget(self.tTableWidget)
        self.tAddButton = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.tAddButton.setObjectName("tAddButton")
        self.verticalLayout_5.addWidget(self.tAddButton)
        self.tDeleteButton = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.tDeleteButton.setObjectName("tDeleteButton")
        self.verticalLayout_5.addWidget(self.tDeleteButton)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label = QtGui.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(20, 30, 381, 17))
        self.label.setObjectName("label")
        self.ServerEdit = QtGui.QLineEdit(self.tab_4)
        self.ServerEdit.setGeometry(QtCore.QRect(40, 50, 411, 27))
        self.ServerEdit.setObjectName("ServerEdit")
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(self.verticalLayoutWidget_2)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(OptionsDialog)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), OptionsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), OptionsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OptionsDialog)

    def retranslateUi(self, OptionsDialog):
        OptionsDialog.setWindowTitle(QtGui.QApplication.translate("OptionsDialog", "Настройки", None, QtGui.QApplication.UnicodeUTF8))
        self.CompanyTableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("OptionsDialog", "Наименование", None, QtGui.QApplication.UnicodeUTF8))
        self.CompanyTableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("OptionsDialog", "ИНН", None, QtGui.QApplication.UnicodeUTF8))
        self.AddButton.setText(QtGui.QApplication.translate("OptionsDialog", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.DeleteButton.setText(QtGui.QApplication.translate("OptionsDialog", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("OptionsDialog", "Компании", None, QtGui.QApplication.UnicodeUTF8))
        self.PovTableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("OptionsDialog", "И.О. Фамилия", None, QtGui.QApplication.UnicodeUTF8))
        self.PovTableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("OptionsDialog", "Доверенность", None, QtGui.QApplication.UnicodeUTF8))
        self.AddPovButton.setText(QtGui.QApplication.translate("OptionsDialog", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.DeletePovButton.setText(QtGui.QApplication.translate("OptionsDialog", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("OptionsDialog", "Поверители", None, QtGui.QApplication.UnicodeUTF8))
        self.PTableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("OptionsDialog", "Модель", None, QtGui.QApplication.UnicodeUTF8))
        self.PAddButton.setText(QtGui.QApplication.translate("OptionsDialog", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.PDeleteButton.setText(QtGui.QApplication.translate("OptionsDialog", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("OptionsDialog", "Методики поверки датчиков давления", None, QtGui.QApplication.UnicodeUTF8))
        self.PMITableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("OptionsDialog", "Сокр. название", None, QtGui.QApplication.UnicodeUTF8))
        self.PMITableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("OptionsDialog", "Строка1", None, QtGui.QApplication.UnicodeUTF8))
        self.PMITableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("OptionsDialog", "Строка2", None, QtGui.QApplication.UnicodeUTF8))
        self.PMITableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("OptionsDialog", "Строка3", None, QtGui.QApplication.UnicodeUTF8))
        self.PMIAddButton.setText(QtGui.QApplication.translate("OptionsDialog", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.PMIDeleteButton.setText(QtGui.QApplication.translate("OptionsDialog", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), QtGui.QApplication.translate("OptionsDialog", "Датчики давления", None, QtGui.QApplication.UnicodeUTF8))
        self.tTableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("OptionsDialog", "Модель", None, QtGui.QApplication.UnicodeUTF8))
        self.tAddButton.setText(QtGui.QApplication.translate("OptionsDialog", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.tDeleteButton.setText(QtGui.QApplication.translate("OptionsDialog", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("OptionsDialog", "Датчики температуры", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("OptionsDialog", "ftp сервер для обновлений:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("OptionsDialog", "Настройки ПО", None, QtGui.QApplication.UnicodeUTF8))

