# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/pressure.ui'
#
# Created: Mon Aug 26 22:05:01 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_PressForm(object):
    def setupUi(self, PressForm):
        PressForm.setObjectName("PressForm")
        PressForm.resize(870, 430)
        PressForm.setMinimumSize(QtCore.QSize(870, 430))
        self.gridLayout_5 = QtGui.QGridLayout(PressForm)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.PrintButton = QtGui.QPushButton(PressForm)
        self.PrintButton.setFlat(False)
        self.PrintButton.setObjectName("PrintButton")
        self.gridLayout_5.addWidget(self.PrintButton, 2, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(PressForm)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.label_19 = QtGui.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(480, 123, 117, 18))
        self.label_19.setObjectName("label_19")
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(480, 279, 220, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)
        self.DayBox = QtGui.QCheckBox(self.layoutWidget)
        self.DayBox.setChecked(True)
        self.DayBox.setObjectName("DayBox")
        self.horizontalLayout.addWidget(self.DayBox)
        self.MonthBox = QtGui.QCheckBox(self.layoutWidget)
        self.MonthBox.setChecked(True)
        self.MonthBox.setObjectName("MonthBox")
        self.horizontalLayout.addWidget(self.MonthBox)
        self.layoutWidget1 = QtGui.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(480, 141, 281, 54))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_21 = QtGui.QLabel(self.layoutWidget1)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.layoutWidget1)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 0, 1, 1, 1)
        self.atmkpa_box = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.atmkpa_box.setDecimals(1)
        self.atmkpa_box.setMinimum(0.0)
        self.atmkpa_box.setMaximum(200.0)
        self.atmkpa_box.setSingleStep(0.5)
        self.atmkpa_box.setProperty("value", 95.3)
        self.atmkpa_box.setObjectName("atmkpa_box")
        self.gridLayout_2.addWidget(self.atmkpa_box, 1, 0, 1, 1)
        self.atmmm_box = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.atmmm_box.setDecimals(0)
        self.atmmm_box.setMinimum(0.0)
        self.atmmm_box.setMaximum(2000.0)
        self.atmmm_box.setSingleStep(1.0)
        self.atmmm_box.setProperty("value", 715.0)
        self.atmmm_box.setObjectName("atmmm_box")
        self.gridLayout_2.addWidget(self.atmmm_box, 1, 1, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(self.tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(480, 57, 281, 64))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_18 = QtGui.QLabel(self.layoutWidget2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 0, 0, 1, 1)
        self.tvos_box = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.tvos_box.setDecimals(0)
        self.tvos_box.setMinimum(0.0)
        self.tvos_box.setMaximum(50.0)
        self.tvos_box.setSingleStep(1.0)
        self.tvos_box.setProperty("value", 23.0)
        self.tvos_box.setObjectName("tvos_box")
        self.gridLayout_3.addWidget(self.tvos_box, 0, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 1, 0, 1, 1)
        self.water_box = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.water_box.setDecimals(0)
        self.water_box.setMinimum(0.0)
        self.water_box.setMaximum(100.0)
        self.water_box.setSingleStep(1.0)
        self.water_box.setProperty("value", 55.0)
        self.water_box.setObjectName("water_box")
        self.gridLayout_3.addWidget(self.water_box, 1, 1, 1, 1)
        self.layoutWidget3 = QtGui.QWidget(self.tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(480, 0, 281, 52))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_17 = QtGui.QLabel(self.layoutWidget3)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.KleimoEdit = QtGui.QLineEdit(self.layoutWidget3)
        self.KleimoEdit.setObjectName("KleimoEdit")
        self.verticalLayout_4.addWidget(self.KleimoEdit)
        self.layoutWidget4 = QtGui.QWidget(self.tab)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 0, 460, 128))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtGui.QLabel(self.layoutWidget4)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.NameBox = QtGui.QComboBox(self.layoutWidget4)
        self.NameBox.setEditable(True)
        self.NameBox.setObjectName("NameBox")
        self.NameBox.addItem("")
        self.NameBox.addItem("")
        self.NameBox.addItem("")
        self.gridLayout_4.addWidget(self.NameBox, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.SerialEdit = QtGui.QLineEdit(self.layoutWidget4)
        self.SerialEdit.setObjectName("SerialEdit")
        self.gridLayout_4.addWidget(self.SerialEdit, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.layoutWidget4)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 3, 0, 1, 1)
        self.INNEdit = QtGui.QLineEdit(self.layoutWidget4)
        self.INNEdit.setObjectName("INNEdit")
        self.gridLayout_4.addWidget(self.INNEdit, 3, 1, 1, 1)
        self.OwnerBox = QtGui.QComboBox(self.layoutWidget4)
        self.OwnerBox.setEditable(True)
        self.OwnerBox.setObjectName("OwnerBox")
        self.OwnerBox.addItem("")
        self.OwnerBox.addItem("")
        self.OwnerBox.addItem("")
        self.OwnerBox.addItem("")
        self.gridLayout_4.addWidget(self.OwnerBox, 2, 1, 1, 1)
        self.layoutWidget5 = QtGui.QWidget(self.tab)
        self.layoutWidget5.setGeometry(QtCore.QRect(0, 130, 460, 161))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_4 = QtGui.QLabel(self.layoutWidget5)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.UnitBox = QtGui.QComboBox(self.layoutWidget5)
        self.UnitBox.setEditable(True)
        self.UnitBox.setObjectName("UnitBox")
        self.UnitBox.addItem("")
        self.UnitBox.addItem("")
        self.UnitBox.addItem("")
        self.UnitBox.addItem("")
        self.UnitBox.addItem("")
        self.gridLayout_6.addWidget(self.UnitBox, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget5)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 2, 0, 1, 1)
        self.minBox = QtGui.QDoubleSpinBox(self.layoutWidget5)
        self.minBox.setDecimals(3)
        self.minBox.setMinimum(-1000000000.0)
        self.minBox.setMaximum(1000000000.0)
        self.minBox.setProperty("value", 0.0)
        self.minBox.setObjectName("minBox")
        self.gridLayout_6.addWidget(self.minBox, 3, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget5)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 0, 1, 1, 1)
        self.KlassBox = QtGui.QDoubleSpinBox(self.layoutWidget5)
        self.KlassBox.setDecimals(3)
        self.KlassBox.setSingleStep(0.25)
        self.KlassBox.setProperty("value", 0.25)
        self.KlassBox.setObjectName("KlassBox")
        self.gridLayout_6.addWidget(self.KlassBox, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget5)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 2, 1, 1, 1)
        self.maxBox = QtGui.QDoubleSpinBox(self.layoutWidget5)
        self.maxBox.setDecimals(3)
        self.maxBox.setMinimum(-1000000000.0)
        self.maxBox.setMaximum(1000000000.0)
        self.maxBox.setProperty("value", 4.0)
        self.maxBox.setObjectName("maxBox")
        self.gridLayout_6.addWidget(self.maxBox, 3, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.layoutWidget5)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 0, 2, 1, 1)
        self.MIBox = QtGui.QComboBox(self.layoutWidget5)
        self.MIBox.setEditable(False)
        self.MIBox.setObjectName("MIBox")
        self.MIBox.addItem("")
        self.MIBox.addItem("")
        self.gridLayout_6.addWidget(self.MIBox, 1, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.layoutWidget5)
        self.label_25.setWordWrap(True)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 2, 2, 1, 1)
        self.interval_box = QtGui.QDoubleSpinBox(self.layoutWidget5)
        self.interval_box.setSuffix("")
        self.interval_box.setDecimals(0)
        self.interval_box.setMinimum(0.0)
        self.interval_box.setMaximum(100.0)
        self.interval_box.setSingleStep(1.0)
        self.interval_box.setProperty("value", 1.0)
        self.interval_box.setObjectName("interval_box")
        self.gridLayout_6.addWidget(self.interval_box, 3, 2, 1, 1)
        self.layoutWidget6 = QtGui.QWidget(self.tab)
        self.layoutWidget6.setGeometry(QtCore.QRect(480, 246, 281, 29))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtGui.QLabel(self.layoutWidget6)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.dateEdit = QtGui.QDateEdit(self.layoutWidget6)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.layoutWidget7 = QtGui.QWidget(self.tab)
        self.layoutWidget7.setGeometry(QtCore.QRect(480, 195, 281, 53))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_16 = QtGui.QLabel(self.layoutWidget7)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.PoverBox = QtGui.QComboBox(self.layoutWidget7)
        self.PoverBox.setEditable(True)
        self.PoverBox.setObjectName("PoverBox")
        self.PoverBox.addItem("")
        self.PoverBox.addItem("")
        self.PoverBox.addItem("")
        self.PoverBox.addItem("")
        self.verticalLayout.addWidget(self.PoverBox)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 36, 841, 280))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.p1Value = QtGui.QLabel(self.gridLayoutWidget)
        self.p1Value.setAlignment(QtCore.Qt.AlignCenter)
        self.p1Value.setObjectName("p1Value")
        self.gridLayout.addWidget(self.p1Value, 5, 0, 1, 1)
        self.p2Value = QtGui.QLabel(self.gridLayoutWidget)
        self.p2Value.setAlignment(QtCore.Qt.AlignCenter)
        self.p2Value.setObjectName("p2Value")
        self.gridLayout.addWidget(self.p2Value, 6, 0, 1, 1)
        self.p3Value = QtGui.QLabel(self.gridLayoutWidget)
        self.p3Value.setAlignment(QtCore.Qt.AlignCenter)
        self.p3Value.setObjectName("p3Value")
        self.gridLayout.addWidget(self.p3Value, 7, 0, 1, 1)
        self.p4Value = QtGui.QLabel(self.gridLayoutWidget)
        self.p4Value.setAlignment(QtCore.Qt.AlignCenter)
        self.p4Value.setObjectName("p4Value")
        self.gridLayout.addWidget(self.p4Value, 8, 0, 1, 1)
        self.p5Value = QtGui.QLabel(self.gridLayoutWidget)
        self.p5Value.setAlignment(QtCore.Qt.AlignCenter)
        self.p5Value.setObjectName("p5Value")
        self.gridLayout.addWidget(self.p5Value, 9, 0, 1, 1)
        self.p6Value = QtGui.QLabel(self.gridLayoutWidget)
        self.p6Value.setAlignment(QtCore.Qt.AlignCenter)
        self.p6Value.setObjectName("p6Value")
        self.gridLayout.addWidget(self.p6Value, 10, 0, 1, 1)
        self.i1Value = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i1Value.sizePolicy().hasHeightForWidth())
        self.i1Value.setSizePolicy(sizePolicy)
        self.i1Value.setAlignment(QtCore.Qt.AlignCenter)
        self.i1Value.setObjectName("i1Value")
        self.gridLayout.addWidget(self.i1Value, 5, 1, 1, 1)
        self.i2Value = QtGui.QLabel(self.gridLayoutWidget)
        self.i2Value.setAlignment(QtCore.Qt.AlignCenter)
        self.i2Value.setObjectName("i2Value")
        self.gridLayout.addWidget(self.i2Value, 6, 1, 1, 1)
        self.i3Value = QtGui.QLabel(self.gridLayoutWidget)
        self.i3Value.setAlignment(QtCore.Qt.AlignCenter)
        self.i3Value.setObjectName("i3Value")
        self.gridLayout.addWidget(self.i3Value, 7, 1, 1, 1)
        self.i4Value = QtGui.QLabel(self.gridLayoutWidget)
        self.i4Value.setAlignment(QtCore.Qt.AlignCenter)
        self.i4Value.setObjectName("i4Value")
        self.gridLayout.addWidget(self.i4Value, 8, 1, 1, 1)
        self.i5Value = QtGui.QLabel(self.gridLayoutWidget)
        self.i5Value.setAlignment(QtCore.Qt.AlignCenter)
        self.i5Value.setObjectName("i5Value")
        self.gridLayout.addWidget(self.i5Value, 9, 1, 1, 1)
        self.i6Value = QtGui.QLabel(self.gridLayoutWidget)
        self.i6Value.setAlignment(QtCore.Qt.AlignCenter)
        self.i6Value.setObjectName("i6Value")
        self.gridLayout.addWidget(self.i6Value, 10, 1, 1, 1)
        self.i1u = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i1u.sizePolicy().hasHeightForWidth())
        self.i1u.setSizePolicy(sizePolicy)
        self.i1u.setDecimals(3)
        self.i1u.setSingleStep(0.001)
        self.i1u.setObjectName("i1u")
        self.gridLayout.addWidget(self.i1u, 5, 2, 1, 1)
        self.i2u = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.i2u.setDecimals(3)
        self.i2u.setSingleStep(0.001)
        self.i2u.setObjectName("i2u")
        self.gridLayout.addWidget(self.i2u, 6, 2, 1, 1)
        self.i3u = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.i3u.setDecimals(3)
        self.i3u.setSingleStep(0.001)
        self.i3u.setObjectName("i3u")
        self.gridLayout.addWidget(self.i3u, 7, 2, 1, 1)
        self.i4u = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.i4u.setDecimals(3)
        self.i4u.setSingleStep(0.001)
        self.i4u.setObjectName("i4u")
        self.gridLayout.addWidget(self.i4u, 8, 2, 1, 1)
        self.i5u = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.i5u.setDecimals(3)
        self.i5u.setSingleStep(0.001)
        self.i5u.setObjectName("i5u")
        self.gridLayout.addWidget(self.i5u, 9, 2, 1, 1)
        self.i6u = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.i6u.setDecimals(3)
        self.i6u.setSingleStep(0.001)
        self.i6u.setObjectName("i6u")
        self.gridLayout.addWidget(self.i6u, 10, 2, 1, 1)
        self.i1d = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i1d.sizePolicy().hasHeightForWidth())
        self.i1d.setSizePolicy(sizePolicy)
        self.i1d.setDecimals(3)
        self.i1d.setSingleStep(0.001)
        self.i1d.setObjectName("i1d")
        self.gridLayout.addWidget(self.i1d, 5, 3, 1, 1)
        self.i2d = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.i2d.setDecimals(3)
        self.i2d.setSingleStep(0.001)
        self.i2d.setObjectName("i2d")
        self.gridLayout.addWidget(self.i2d, 6, 3, 1, 1)
        self.i3d = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.i3d.setDecimals(3)
        self.i3d.setSingleStep(0.001)
        self.i3d.setObjectName("i3d")
        self.gridLayout.addWidget(self.i3d, 7, 3, 1, 1)
        self.i4d = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.i4d.setDecimals(3)
        self.i4d.setSingleStep(0.001)
        self.i4d.setObjectName("i4d")
        self.gridLayout.addWidget(self.i4d, 8, 3, 1, 1)
        self.i5d = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.i5d.setDecimals(3)
        self.i5d.setSingleStep(0.001)
        self.i5d.setObjectName("i5d")
        self.gridLayout.addWidget(self.i5d, 9, 3, 1, 1)
        self.i6d = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.i6d.setDecimals(3)
        self.i6d.setSingleStep(0.001)
        self.i6d.setObjectName("i6d")
        self.gridLayout.addWidget(self.i6d, 10, 3, 1, 1)
        self.du1 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.du1.sizePolicy().hasHeightForWidth())
        self.du1.setSizePolicy(sizePolicy)
        self.du1.setAlignment(QtCore.Qt.AlignCenter)
        self.du1.setObjectName("du1")
        self.gridLayout.addWidget(self.du1, 5, 4, 1, 1)
        self.du2 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.du2.sizePolicy().hasHeightForWidth())
        self.du2.setSizePolicy(sizePolicy)
        self.du2.setAlignment(QtCore.Qt.AlignCenter)
        self.du2.setObjectName("du2")
        self.gridLayout.addWidget(self.du2, 6, 4, 1, 1)
        self.du3 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.du3.sizePolicy().hasHeightForWidth())
        self.du3.setSizePolicy(sizePolicy)
        self.du3.setAlignment(QtCore.Qt.AlignCenter)
        self.du3.setObjectName("du3")
        self.gridLayout.addWidget(self.du3, 7, 4, 1, 1)
        self.du4 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.du4.sizePolicy().hasHeightForWidth())
        self.du4.setSizePolicy(sizePolicy)
        self.du4.setAlignment(QtCore.Qt.AlignCenter)
        self.du4.setObjectName("du4")
        self.gridLayout.addWidget(self.du4, 8, 4, 1, 1)
        self.du5 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.du5.sizePolicy().hasHeightForWidth())
        self.du5.setSizePolicy(sizePolicy)
        self.du5.setAlignment(QtCore.Qt.AlignCenter)
        self.du5.setObjectName("du5")
        self.gridLayout.addWidget(self.du5, 9, 4, 1, 1)
        self.du6 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.du6.sizePolicy().hasHeightForWidth())
        self.du6.setSizePolicy(sizePolicy)
        self.du6.setAlignment(QtCore.Qt.AlignCenter)
        self.du6.setObjectName("du6")
        self.gridLayout.addWidget(self.du6, 10, 4, 1, 1)
        self.dd1 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dd1.sizePolicy().hasHeightForWidth())
        self.dd1.setSizePolicy(sizePolicy)
        self.dd1.setAlignment(QtCore.Qt.AlignCenter)
        self.dd1.setObjectName("dd1")
        self.gridLayout.addWidget(self.dd1, 5, 5, 1, 1)
        self.dd2 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dd2.sizePolicy().hasHeightForWidth())
        self.dd2.setSizePolicy(sizePolicy)
        self.dd2.setAlignment(QtCore.Qt.AlignCenter)
        self.dd2.setObjectName("dd2")
        self.gridLayout.addWidget(self.dd2, 6, 5, 1, 1)
        self.dd3 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dd3.sizePolicy().hasHeightForWidth())
        self.dd3.setSizePolicy(sizePolicy)
        self.dd3.setAlignment(QtCore.Qt.AlignCenter)
        self.dd3.setObjectName("dd3")
        self.gridLayout.addWidget(self.dd3, 7, 5, 1, 1)
        self.dd4 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dd4.sizePolicy().hasHeightForWidth())
        self.dd4.setSizePolicy(sizePolicy)
        self.dd4.setAlignment(QtCore.Qt.AlignCenter)
        self.dd4.setObjectName("dd4")
        self.gridLayout.addWidget(self.dd4, 8, 5, 1, 1)
        self.dd5 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dd5.sizePolicy().hasHeightForWidth())
        self.dd5.setSizePolicy(sizePolicy)
        self.dd5.setAlignment(QtCore.Qt.AlignCenter)
        self.dd5.setObjectName("dd5")
        self.gridLayout.addWidget(self.dd5, 9, 5, 1, 1)
        self.dd6 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dd6.sizePolicy().hasHeightForWidth())
        self.dd6.setSizePolicy(sizePolicy)
        self.dd6.setAlignment(QtCore.Qt.AlignCenter)
        self.dd6.setObjectName("dd6")
        self.gridLayout.addWidget(self.dd6, 10, 5, 1, 1)
        self.v1 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v1.sizePolicy().hasHeightForWidth())
        self.v1.setSizePolicy(sizePolicy)
        self.v1.setAlignment(QtCore.Qt.AlignCenter)
        self.v1.setObjectName("v1")
        self.gridLayout.addWidget(self.v1, 5, 6, 1, 1)
        self.v2 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v2.sizePolicy().hasHeightForWidth())
        self.v2.setSizePolicy(sizePolicy)
        self.v2.setAlignment(QtCore.Qt.AlignCenter)
        self.v2.setObjectName("v2")
        self.gridLayout.addWidget(self.v2, 6, 6, 1, 1)
        self.v3 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v3.sizePolicy().hasHeightForWidth())
        self.v3.setSizePolicy(sizePolicy)
        self.v3.setAlignment(QtCore.Qt.AlignCenter)
        self.v3.setObjectName("v3")
        self.gridLayout.addWidget(self.v3, 7, 6, 1, 1)
        self.v4 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v4.sizePolicy().hasHeightForWidth())
        self.v4.setSizePolicy(sizePolicy)
        self.v4.setAlignment(QtCore.Qt.AlignCenter)
        self.v4.setObjectName("v4")
        self.gridLayout.addWidget(self.v4, 8, 6, 1, 1)
        self.v5 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v5.sizePolicy().hasHeightForWidth())
        self.v5.setSizePolicy(sizePolicy)
        self.v5.setAlignment(QtCore.Qt.AlignCenter)
        self.v5.setObjectName("v5")
        self.gridLayout.addWidget(self.v5, 9, 6, 1, 1)
        self.v6 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v6.sizePolicy().hasHeightForWidth())
        self.v6.setSizePolicy(sizePolicy)
        self.v6.setAlignment(QtCore.Qt.AlignCenter)
        self.v6.setObjectName("v6")
        self.gridLayout.addWidget(self.v6, 10, 6, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 2, 1, 1)
        self.label_26 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 3, 4, 2, 1)
        self.label_27 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setWordWrap(True)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 3, 5, 2, 1)
        self.label_28 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 3, 6, 2, 1)
        self.label_maxd = QtGui.QLabel(self.gridLayoutWidget)
        self.label_maxd.setAlignment(QtCore.Qt.AlignCenter)
        self.label_maxd.setObjectName("label_maxd")
        self.gridLayout.addWidget(self.label_maxd, 11, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setWordWrap(True)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 11, 0, 1, 1)
        self.label_maxv = QtGui.QLabel(self.gridLayoutWidget)
        self.label_maxv.setAlignment(QtCore.Qt.AlignCenter)
        self.label_maxv.setObjectName("label_maxv")
        self.gridLayout.addWidget(self.label_maxv, 11, 3, 1, 1)
        self.label_30 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 11, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(10, 9, 111, 18))
        self.label_7.setObjectName("label_7")
        self.col_pointsBox = QtGui.QSpinBox(self.tab_2)
        self.col_pointsBox.setGeometry(QtCore.QRect(132, 6, 51, 28))
        self.col_pointsBox.setMinimum(5)
        self.col_pointsBox.setMaximum(6)
        self.col_pointsBox.setObjectName("col_pointsBox")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.statusLabel = QtGui.QLabel(PressForm)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.statusLabel.setPalette(palette)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout_5.addWidget(self.statusLabel, 3, 0, 1, 1)

        self.retranslateUi(PressForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PressForm)
        PressForm.setTabOrder(self.NameBox, self.SerialEdit)
        PressForm.setTabOrder(self.SerialEdit, self.OwnerBox)
        PressForm.setTabOrder(self.OwnerBox, self.INNEdit)
        PressForm.setTabOrder(self.INNEdit, self.UnitBox)
        PressForm.setTabOrder(self.UnitBox, self.KlassBox)
        PressForm.setTabOrder(self.KlassBox, self.MIBox)
        PressForm.setTabOrder(self.MIBox, self.minBox)
        PressForm.setTabOrder(self.minBox, self.maxBox)
        PressForm.setTabOrder(self.maxBox, self.interval_box)
        PressForm.setTabOrder(self.interval_box, self.KleimoEdit)
        PressForm.setTabOrder(self.KleimoEdit, self.tvos_box)
        PressForm.setTabOrder(self.tvos_box, self.water_box)
        PressForm.setTabOrder(self.water_box, self.atmkpa_box)
        PressForm.setTabOrder(self.atmkpa_box, self.atmmm_box)
        PressForm.setTabOrder(self.atmmm_box, self.PoverBox)
        PressForm.setTabOrder(self.PoverBox, self.dateEdit)
        PressForm.setTabOrder(self.dateEdit, self.DayBox)
        PressForm.setTabOrder(self.DayBox, self.MonthBox)
        PressForm.setTabOrder(self.MonthBox, self.tabWidget)
        PressForm.setTabOrder(self.tabWidget, self.col_pointsBox)
        PressForm.setTabOrder(self.col_pointsBox, self.i1u)
        PressForm.setTabOrder(self.i1u, self.i2u)
        PressForm.setTabOrder(self.i2u, self.i3u)
        PressForm.setTabOrder(self.i3u, self.i4u)
        PressForm.setTabOrder(self.i4u, self.i5u)
        PressForm.setTabOrder(self.i5u, self.i6u)
        PressForm.setTabOrder(self.i6u, self.i6d)
        PressForm.setTabOrder(self.i6d, self.i5d)
        PressForm.setTabOrder(self.i5d, self.i4d)
        PressForm.setTabOrder(self.i4d, self.i3d)
        PressForm.setTabOrder(self.i3d, self.i2d)
        PressForm.setTabOrder(self.i2d, self.i1d)
        PressForm.setTabOrder(self.i1d, self.PrintButton)

    def retranslateUi(self, PressForm):
        PressForm.setWindowTitle(QtGui.QApplication.translate("PressForm", "Поверка", None, QtGui.QApplication.UnicodeUTF8))
        self.PrintButton.setText(QtGui.QApplication.translate("PressForm", "Протокол...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("PressForm", "атм. давление", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("PressForm", "Печатать:", None, QtGui.QApplication.UnicodeUTF8))
        self.DayBox.setText(QtGui.QApplication.translate("PressForm", "день", None, QtGui.QApplication.UnicodeUTF8))
        self.MonthBox.setText(QtGui.QApplication.translate("PressForm", "месяц", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("PressForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">84÷106,7 кПа</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("PressForm", "630÷800 мм.рт.ст", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("PressForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">темп. воздуха (23±2), °C</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("PressForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">влажность (30÷80), %</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("PressForm", "Номер клейма предыдущей поверки", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PressForm", "Тип", None, QtGui.QApplication.UnicodeUTF8))
        self.NameBox.setItemText(0, QtGui.QApplication.translate("PressForm", "FR 3051", None, QtGui.QApplication.UnicodeUTF8))
        self.NameBox.setItemText(1, QtGui.QApplication.translate("PressForm", "Метран", None, QtGui.QApplication.UnicodeUTF8))
        self.NameBox.setItemText(2, QtGui.QApplication.translate("PressForm", "Сапфир", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PressForm", "Заводской №", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("PressForm", "Принадлеж.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("PressForm", "ИНН", None, QtGui.QApplication.UnicodeUTF8))
        self.OwnerBox.setItemText(0, QtGui.QApplication.translate("PressForm", "ОАО \"СН-МНГ\"", None, QtGui.QApplication.UnicodeUTF8))
        self.OwnerBox.setItemText(1, QtGui.QApplication.translate("PressForm", "ОАО \"ТНК-Нижневартовск\"", None, QtGui.QApplication.UnicodeUTF8))
        self.OwnerBox.setItemText(2, QtGui.QApplication.translate("PressForm", "ОАО \"СНГДУ-2\"", None, QtGui.QApplication.UnicodeUTF8))
        self.OwnerBox.setItemText(3, QtGui.QApplication.translate("PressForm", "ОАО \"СНГ\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("PressForm", "ед. измерения", None, QtGui.QApplication.UnicodeUTF8))
        self.UnitBox.setItemText(0, QtGui.QApplication.translate("PressForm", "МПа", None, QtGui.QApplication.UnicodeUTF8))
        self.UnitBox.setItemText(1, QtGui.QApplication.translate("PressForm", "бар", None, QtGui.QApplication.UnicodeUTF8))
        self.UnitBox.setItemText(2, QtGui.QApplication.translate("PressForm", "кПа", None, QtGui.QApplication.UnicodeUTF8))
        self.UnitBox.setItemText(3, QtGui.QApplication.translate("PressForm", "кгс/см2", None, QtGui.QApplication.UnicodeUTF8))
        self.UnitBox.setItemText(4, QtGui.QApplication.translate("PressForm", "мм. рт. ст", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("PressForm", "Нижний предел", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("PressForm", "Класс точности", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("PressForm", "Верхний предел", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("PressForm", "Методика поверки", None, QtGui.QApplication.UnicodeUTF8))
        self.MIBox.setItemText(0, QtGui.QApplication.translate("PressForm", "МИ 1997-89", None, QtGui.QApplication.UnicodeUTF8))
        self.MIBox.setItemText(1, QtGui.QApplication.translate("PressForm", "МИ 4212-012-2001", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("PressForm", "Межповерочный\n"
"интервал", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("PressForm", "Дата", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("PressForm", "Поверитель", None, QtGui.QApplication.UnicodeUTF8))
        self.PoverBox.setItemText(0, QtGui.QApplication.translate("PressForm", "О. П. Голуб", None, QtGui.QApplication.UnicodeUTF8))
        self.PoverBox.setItemText(1, QtGui.QApplication.translate("PressForm", "Е. В. Денис", None, QtGui.QApplication.UnicodeUTF8))
        self.PoverBox.setItemText(2, QtGui.QApplication.translate("PressForm", "Н. В. Григорьева", None, QtGui.QApplication.UnicodeUTF8))
        self.PoverBox.setItemText(3, QtGui.QApplication.translate("PressForm", "С. В. Багаева", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("PressForm", "Датчик и протокол", None, QtGui.QApplication.UnicodeUTF8))
        self.p1Value.setText(QtGui.QApplication.translate("PressForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.p2Value.setText(QtGui.QApplication.translate("PressForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.p3Value.setText(QtGui.QApplication.translate("PressForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.p4Value.setText(QtGui.QApplication.translate("PressForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.p5Value.setText(QtGui.QApplication.translate("PressForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.p6Value.setText(QtGui.QApplication.translate("PressForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.i1Value.setText(QtGui.QApplication.translate("PressForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.i2Value.setText(QtGui.QApplication.translate("PressForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.i3Value.setText(QtGui.QApplication.translate("PressForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.i4Value.setText(QtGui.QApplication.translate("PressForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.i5Value.setText(QtGui.QApplication.translate("PressForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.i6Value.setText(QtGui.QApplication.translate("PressForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.du1.setText(QtGui.QApplication.translate("PressForm", "0,000 мА (0,00%)", None, QtGui.QApplication.UnicodeUTF8))
        self.du2.setText(QtGui.QApplication.translate("PressForm", "0,000 мА (0,00%)", None, QtGui.QApplication.UnicodeUTF8))
        self.du3.setText(QtGui.QApplication.translate("PressForm", "0,000 мА (0,00%)", None, QtGui.QApplication.UnicodeUTF8))
        self.du4.setText(QtGui.QApplication.translate("PressForm", "0,000 мА (0,00%)", None, QtGui.QApplication.UnicodeUTF8))
        self.du5.setText(QtGui.QApplication.translate("PressForm", "0,000 мА (0,00%)", None, QtGui.QApplication.UnicodeUTF8))
        self.du6.setText(QtGui.QApplication.translate("PressForm", "0,000 мА (0,00%)", None, QtGui.QApplication.UnicodeUTF8))
        self.dd1.setText(QtGui.QApplication.translate("PressForm", "0,000 мА (0,00%)", None, QtGui.QApplication.UnicodeUTF8))
        self.dd2.setText(QtGui.QApplication.translate("PressForm", "0,000 мА (0,00%)", None, QtGui.QApplication.UnicodeUTF8))
        self.dd3.setText(QtGui.QApplication.translate("PressForm", "0,000 мА (0,00%)", None, QtGui.QApplication.UnicodeUTF8))
        self.dd4.setText(QtGui.QApplication.translate("PressForm", "0,000 мА (0,00%)", None, QtGui.QApplication.UnicodeUTF8))
        self.dd5.setText(QtGui.QApplication.translate("PressForm", "0,000 мА (0,00%)", None, QtGui.QApplication.UnicodeUTF8))
        self.dd6.setText(QtGui.QApplication.translate("PressForm", "0,000 мА (0,00%)", None, QtGui.QApplication.UnicodeUTF8))
        self.v1.setText(QtGui.QApplication.translate("PressForm", "0,000 мА (0,00%)", None, QtGui.QApplication.UnicodeUTF8))
        self.v2.setText(QtGui.QApplication.translate("PressForm", "0,000 мА (0,00%)", None, QtGui.QApplication.UnicodeUTF8))
        self.v3.setText(QtGui.QApplication.translate("PressForm", "0,000 мА (0,00%)", None, QtGui.QApplication.UnicodeUTF8))
        self.v4.setText(QtGui.QApplication.translate("PressForm", "0,000 мА (0,00%)", None, QtGui.QApplication.UnicodeUTF8))
        self.v5.setText(QtGui.QApplication.translate("PressForm", "0,000 мА (0,00%)", None, QtGui.QApplication.UnicodeUTF8))
        self.v6.setText(QtGui.QApplication.translate("PressForm", "0,000 мА (0,00%)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("PressForm", "обр. ход", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("PressForm", "Пр. ход", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("PressForm", "Расч. ток", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("PressForm", "Заданное\n"
"давление", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("PressForm", "измереннный ток", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("PressForm", "Прямой ход", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("PressForm", "Обратный ход", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("PressForm", "Вариация", None, QtGui.QApplication.UnicodeUTF8))
        self.label_maxd.setText(QtGui.QApplication.translate("PressForm", "0,00%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("PressForm", "Макс. погр.:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_maxv.setText(QtGui.QApplication.translate("PressForm", "0,00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("PressForm", "Макс. вар.:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("PressForm", "Кол-во точек", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("PressForm", "Измерения", None, QtGui.QApplication.UnicodeUTF8))

