# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/temperature.ui'
#
# Created: Fri Aug 16 21:58:42 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_TempForm(object):
    def setupUi(self, TempForm):
        TempForm.setObjectName("TempForm")
        TempForm.resize(724, 450)
        TempForm.setMinimumSize(QtCore.QSize(724, 450))
        self.verticalLayout = QtGui.QVBoxLayout(TempForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(TempForm)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(100, 250, 149, 21))
        self.label_7.setObjectName("label_7")
        self.label_24 = QtGui.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(50, 170, 261, 20))
        self.label_24.setObjectName("label_24")
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(400, 10, 281, 52))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.KleimoEdit = QtGui.QLineEdit(self.layoutWidget)
        self.KleimoEdit.setObjectName("KleimoEdit")
        self.verticalLayout_4.addWidget(self.KleimoEdit)
        self.layoutWidget_2 = QtGui.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(400, 70, 281, 64))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_18 = QtGui.QLabel(self.layoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 0, 0, 1, 1)
        self.tvos_box = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.tvos_box.setDecimals(0)
        self.tvos_box.setMinimum(0.0)
        self.tvos_box.setMaximum(50.0)
        self.tvos_box.setSingleStep(1.0)
        self.tvos_box.setProperty("value", 23.0)
        self.tvos_box.setObjectName("tvos_box")
        self.gridLayout_5.addWidget(self.tvos_box, 0, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 1, 0, 1, 1)
        self.water_box = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.water_box.setDecimals(0)
        self.water_box.setMinimum(0.0)
        self.water_box.setMaximum(100.0)
        self.water_box.setSingleStep(1.0)
        self.water_box.setProperty("value", 55.0)
        self.water_box.setObjectName("water_box")
        self.gridLayout_5.addWidget(self.water_box, 1, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(400, 140, 117, 18))
        self.label_19.setObjectName("label_19")
        self.layoutWidget_3 = QtGui.QWidget(self.tab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(400, 160, 281, 54))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_25 = QtGui.QLabel(self.layoutWidget_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 0, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.layoutWidget_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 0, 1, 1, 1)
        self.atmkpa_box = QtGui.QDoubleSpinBox(self.layoutWidget_3)
        self.atmkpa_box.setDecimals(1)
        self.atmkpa_box.setMinimum(0.0)
        self.atmkpa_box.setMaximum(200.0)
        self.atmkpa_box.setSingleStep(0.5)
        self.atmkpa_box.setProperty("value", 101.3)
        self.atmkpa_box.setObjectName("atmkpa_box")
        self.gridLayout_6.addWidget(self.atmkpa_box, 1, 0, 1, 1)
        self.atmmm_box = QtGui.QDoubleSpinBox(self.layoutWidget_3)
        self.atmmm_box.setDecimals(0)
        self.atmmm_box.setMinimum(0.0)
        self.atmmm_box.setMaximum(2000.0)
        self.atmmm_box.setSingleStep(1.0)
        self.atmmm_box.setProperty("value", 760.0)
        self.atmmm_box.setObjectName("atmmm_box")
        self.gridLayout_6.addWidget(self.atmmm_box, 1, 1, 1, 1)
        self.layoutWidget_4 = QtGui.QWidget(self.tab)
        self.layoutWidget_4.setGeometry(QtCore.QRect(400, 220, 281, 53))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_16 = QtGui.QLabel(self.layoutWidget_4)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.PoverBox = QtGui.QComboBox(self.layoutWidget_4)
        self.PoverBox.setEditable(True)
        self.PoverBox.setObjectName("PoverBox")
        self.PoverBox.addItem("")
        self.PoverBox.addItem("")
        self.PoverBox.addItem("")
        self.PoverBox.addItem("")
        self.verticalLayout_2.addWidget(self.PoverBox)
        self.layoutWidget_5 = QtGui.QWidget(self.tab)
        self.layoutWidget_5.setGeometry(QtCore.QRect(400, 280, 281, 28))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtGui.QLabel(self.layoutWidget_5)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.dateEdit = QtGui.QDateEdit(self.layoutWidget_5)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.layoutWidget_6 = QtGui.QWidget(self.tab)
        self.layoutWidget_6.setGeometry(QtCore.QRect(400, 320, 216, 25))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_15 = QtGui.QLabel(self.layoutWidget_6)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)
        self.DayBox = QtGui.QCheckBox(self.layoutWidget_6)
        self.DayBox.setChecked(True)
        self.DayBox.setObjectName("DayBox")
        self.horizontalLayout.addWidget(self.DayBox)
        self.MonthBox = QtGui.QCheckBox(self.layoutWidget_6)
        self.MonthBox.setChecked(True)
        self.MonthBox.setObjectName("MonthBox")
        self.horizontalLayout.addWidget(self.MonthBox)
        self.layoutWidget1 = QtGui.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(6, 6, 386, 158))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.NameBox = QtGui.QComboBox(self.layoutWidget1)
        self.NameBox.setEditable(True)
        self.NameBox.setObjectName("NameBox")
        self.NameBox.addItem("")
        self.NameBox.addItem("")
        self.NameBox.addItem("")
        self.NameBox.addItem("")
        self.gridLayout_2.addWidget(self.NameBox, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.SerialEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.SerialEdit.setObjectName("SerialEdit")
        self.gridLayout_2.addWidget(self.SerialEdit, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.SerialEdit_2 = QtGui.QLineEdit(self.layoutWidget1)
        self.SerialEdit_2.setObjectName("SerialEdit_2")
        self.gridLayout_2.addWidget(self.SerialEdit_2, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.OwnerBox = QtGui.QComboBox(self.layoutWidget1)
        self.OwnerBox.setMaximumSize(QtCore.QSize(16777215, 16777212))
        self.OwnerBox.setEditable(True)
        self.OwnerBox.setObjectName("OwnerBox")
        self.OwnerBox.addItem("")
        self.OwnerBox.addItem("")
        self.OwnerBox.addItem("")
        self.OwnerBox.addItem("")
        self.OwnerBox.addItem("")
        self.gridLayout_2.addWidget(self.OwnerBox, 3, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.layoutWidget1)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 4, 0, 1, 1)
        self.INNEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.INNEdit.setObjectName("INNEdit")
        self.gridLayout_2.addWidget(self.INNEdit, 4, 1, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(self.tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 190, 331, 64))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.maxBox = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.maxBox.setDecimals(3)
        self.maxBox.setMaximum(10000.0)
        self.maxBox.setProperty("value", 50.0)
        self.maxBox.setObjectName("maxBox")
        self.gridLayout_3.addWidget(self.maxBox, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.minBox = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.minBox.setDecimals(3)
        self.minBox.setMinimum(-10000.0)
        self.minBox.setMaximum(10000.0)
        self.minBox.setProperty("value", 0.0)
        self.minBox.setObjectName("minBox")
        self.gridLayout_3.addWidget(self.minBox, 1, 0, 1, 1)
        self.layoutWidget3 = QtGui.QWidget(self.tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 280, 341, 71))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_23 = QtGui.QLabel(self.layoutWidget3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 0, 1, 1, 1)
        self.pmaxBox = QtGui.QDoubleSpinBox(self.layoutWidget3)
        self.pmaxBox.setDecimals(3)
        self.pmaxBox.setMaximum(150.0)
        self.pmaxBox.setProperty("value", 50.0)
        self.pmaxBox.setObjectName("pmaxBox")
        self.gridLayout_4.addWidget(self.pmaxBox, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.pminBox = QtGui.QDoubleSpinBox(self.layoutWidget3)
        self.pminBox.setDecimals(3)
        self.pminBox.setMinimum(-50.0)
        self.pminBox.setMaximum(10000.0)
        self.pminBox.setProperty("value", 0.0)
        self.pminBox.setObjectName("pminBox")
        self.gridLayout_4.addWidget(self.pminBox, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-10, 70, 704, 280))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.p1Value = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p1Value.sizePolicy().hasHeightForWidth())
        self.p1Value.setSizePolicy(sizePolicy)
        self.p1Value.setAlignment(QtCore.Qt.AlignCenter)
        self.p1Value.setObjectName("p1Value")
        self.gridLayout.addWidget(self.p1Value, 5, 0, 1, 1)
        self.p2Value = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p2Value.sizePolicy().hasHeightForWidth())
        self.p2Value.setSizePolicy(sizePolicy)
        self.p2Value.setAlignment(QtCore.Qt.AlignCenter)
        self.p2Value.setObjectName("p2Value")
        self.gridLayout.addWidget(self.p2Value, 6, 0, 1, 1)
        self.p3Value = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p3Value.sizePolicy().hasHeightForWidth())
        self.p3Value.setSizePolicy(sizePolicy)
        self.p3Value.setAlignment(QtCore.Qt.AlignCenter)
        self.p3Value.setObjectName("p3Value")
        self.gridLayout.addWidget(self.p3Value, 7, 0, 1, 1)
        self.p4Value = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p4Value.sizePolicy().hasHeightForWidth())
        self.p4Value.setSizePolicy(sizePolicy)
        self.p4Value.setAlignment(QtCore.Qt.AlignCenter)
        self.p4Value.setObjectName("p4Value")
        self.gridLayout.addWidget(self.p4Value, 8, 0, 1, 1)
        self.p5Value = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p5Value.sizePolicy().hasHeightForWidth())
        self.p5Value.setSizePolicy(sizePolicy)
        self.p5Value.setAlignment(QtCore.Qt.AlignCenter)
        self.p5Value.setObjectName("p5Value")
        self.gridLayout.addWidget(self.p5Value, 9, 0, 1, 1)
        self.p6Value = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p6Value.sizePolicy().hasHeightForWidth())
        self.p6Value.setSizePolicy(sizePolicy)
        self.p6Value.setAlignment(QtCore.Qt.AlignCenter)
        self.p6Value.setObjectName("p6Value")
        self.gridLayout.addWidget(self.p6Value, 10, 0, 1, 1)
        self.i1 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i1.sizePolicy().hasHeightForWidth())
        self.i1.setSizePolicy(sizePolicy)
        self.i1.setDecimals(3)
        self.i1.setSingleStep(0.001)
        self.i1.setProperty("value", 4.0)
        self.i1.setObjectName("i1")
        self.gridLayout.addWidget(self.i1, 5, 2, 1, 1)
        self.i2 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i2.sizePolicy().hasHeightForWidth())
        self.i2.setSizePolicy(sizePolicy)
        self.i2.setDecimals(3)
        self.i2.setSingleStep(0.001)
        self.i2.setProperty("value", 7.2)
        self.i2.setObjectName("i2")
        self.gridLayout.addWidget(self.i2, 6, 2, 1, 1)
        self.i3 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i3.sizePolicy().hasHeightForWidth())
        self.i3.setSizePolicy(sizePolicy)
        self.i3.setDecimals(3)
        self.i3.setSingleStep(0.001)
        self.i3.setProperty("value", 10.4)
        self.i3.setObjectName("i3")
        self.gridLayout.addWidget(self.i3, 7, 2, 1, 1)
        self.i4 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i4.sizePolicy().hasHeightForWidth())
        self.i4.setSizePolicy(sizePolicy)
        self.i4.setDecimals(3)
        self.i4.setSingleStep(0.001)
        self.i4.setProperty("value", 13.6)
        self.i4.setObjectName("i4")
        self.gridLayout.addWidget(self.i4, 8, 2, 1, 1)
        self.i5 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i5.sizePolicy().hasHeightForWidth())
        self.i5.setSizePolicy(sizePolicy)
        self.i5.setDecimals(3)
        self.i5.setSingleStep(0.001)
        self.i5.setProperty("value", 16.8)
        self.i5.setObjectName("i5")
        self.gridLayout.addWidget(self.i5, 9, 2, 1, 1)
        self.i6 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i6.sizePolicy().hasHeightForWidth())
        self.i6.setSizePolicy(sizePolicy)
        self.i6.setDecimals(3)
        self.i6.setSingleStep(0.001)
        self.i6.setProperty("value", 20.0)
        self.i6.setObjectName("i6")
        self.gridLayout.addWidget(self.i6, 10, 2, 1, 1)
        self.du1 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.du1.sizePolicy().hasHeightForWidth())
        self.du1.setSizePolicy(sizePolicy)
        self.du1.setText("")
        self.du1.setAlignment(QtCore.Qt.AlignCenter)
        self.du1.setObjectName("du1")
        self.gridLayout.addWidget(self.du1, 5, 4, 1, 1)
        self.du2 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.du2.sizePolicy().hasHeightForWidth())
        self.du2.setSizePolicy(sizePolicy)
        self.du2.setText("")
        self.du2.setAlignment(QtCore.Qt.AlignCenter)
        self.du2.setObjectName("du2")
        self.gridLayout.addWidget(self.du2, 6, 4, 1, 1)
        self.du3 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.du3.sizePolicy().hasHeightForWidth())
        self.du3.setSizePolicy(sizePolicy)
        self.du3.setText("")
        self.du3.setAlignment(QtCore.Qt.AlignCenter)
        self.du3.setObjectName("du3")
        self.gridLayout.addWidget(self.du3, 7, 4, 1, 1)
        self.du4 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.du4.sizePolicy().hasHeightForWidth())
        self.du4.setSizePolicy(sizePolicy)
        self.du4.setText("")
        self.du4.setAlignment(QtCore.Qt.AlignCenter)
        self.du4.setObjectName("du4")
        self.gridLayout.addWidget(self.du4, 8, 4, 1, 1)
        self.du5 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.du5.sizePolicy().hasHeightForWidth())
        self.du5.setSizePolicy(sizePolicy)
        self.du5.setText("")
        self.du5.setAlignment(QtCore.Qt.AlignCenter)
        self.du5.setObjectName("du5")
        self.gridLayout.addWidget(self.du5, 9, 4, 1, 1)
        self.du6 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.du6.sizePolicy().hasHeightForWidth())
        self.du6.setSizePolicy(sizePolicy)
        self.du6.setText("")
        self.du6.setAlignment(QtCore.Qt.AlignCenter)
        self.du6.setObjectName("du6")
        self.gridLayout.addWidget(self.du6, 10, 4, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 4, 4, 1, 1)
        self.t1 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1.sizePolicy().hasHeightForWidth())
        self.t1.setSizePolicy(sizePolicy)
        self.t1.setDecimals(2)
        self.t1.setMinimum(-200.0)
        self.t1.setMaximum(200.0)
        self.t1.setSingleStep(0.01)
        self.t1.setObjectName("t1")
        self.gridLayout.addWidget(self.t1, 5, 1, 1, 1)
        self.t2 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t2.sizePolicy().hasHeightForWidth())
        self.t2.setSizePolicy(sizePolicy)
        self.t2.setDecimals(2)
        self.t2.setMinimum(-200.0)
        self.t2.setMaximum(200.0)
        self.t2.setSingleStep(0.01)
        self.t2.setObjectName("t2")
        self.gridLayout.addWidget(self.t2, 6, 1, 1, 1)
        self.t3 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t3.sizePolicy().hasHeightForWidth())
        self.t3.setSizePolicy(sizePolicy)
        self.t3.setDecimals(2)
        self.t3.setMinimum(-200.0)
        self.t3.setMaximum(200.0)
        self.t3.setSingleStep(0.01)
        self.t3.setObjectName("t3")
        self.gridLayout.addWidget(self.t3, 7, 1, 1, 1)
        self.i1Value = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i1Value.sizePolicy().hasHeightForWidth())
        self.i1Value.setSizePolicy(sizePolicy)
        self.i1Value.setAlignment(QtCore.Qt.AlignCenter)
        self.i1Value.setObjectName("i1Value")
        self.gridLayout.addWidget(self.i1Value, 5, 3, 1, 1)
        self.i2Value = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i2Value.sizePolicy().hasHeightForWidth())
        self.i2Value.setSizePolicy(sizePolicy)
        self.i2Value.setAlignment(QtCore.Qt.AlignCenter)
        self.i2Value.setObjectName("i2Value")
        self.gridLayout.addWidget(self.i2Value, 6, 3, 1, 1)
        self.i3Value = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i3Value.sizePolicy().hasHeightForWidth())
        self.i3Value.setSizePolicy(sizePolicy)
        self.i3Value.setAlignment(QtCore.Qt.AlignCenter)
        self.i3Value.setObjectName("i3Value")
        self.gridLayout.addWidget(self.i3Value, 7, 3, 1, 1)
        self.t4 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t4.sizePolicy().hasHeightForWidth())
        self.t4.setSizePolicy(sizePolicy)
        self.t4.setDecimals(2)
        self.t4.setMinimum(-200.0)
        self.t4.setMaximum(200.0)
        self.t4.setSingleStep(0.01)
        self.t4.setObjectName("t4")
        self.gridLayout.addWidget(self.t4, 8, 1, 1, 1)
        self.t5 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t5.sizePolicy().hasHeightForWidth())
        self.t5.setSizePolicy(sizePolicy)
        self.t5.setDecimals(2)
        self.t5.setMinimum(-200.0)
        self.t5.setMaximum(200.0)
        self.t5.setSingleStep(0.01)
        self.t5.setObjectName("t5")
        self.gridLayout.addWidget(self.t5, 9, 1, 1, 1)
        self.t6 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t6.sizePolicy().hasHeightForWidth())
        self.t6.setSizePolicy(sizePolicy)
        self.t6.setDecimals(2)
        self.t6.setMinimum(-200.0)
        self.t6.setMaximum(200.0)
        self.t6.setSingleStep(0.01)
        self.t6.setObjectName("t6")
        self.gridLayout.addWidget(self.t6, 10, 1, 1, 1)
        self.i4Value = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i4Value.sizePolicy().hasHeightForWidth())
        self.i4Value.setSizePolicy(sizePolicy)
        self.i4Value.setAlignment(QtCore.Qt.AlignCenter)
        self.i4Value.setObjectName("i4Value")
        self.gridLayout.addWidget(self.i4Value, 8, 3, 1, 1)
        self.i5Value = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i5Value.sizePolicy().hasHeightForWidth())
        self.i5Value.setSizePolicy(sizePolicy)
        self.i5Value.setAlignment(QtCore.Qt.AlignCenter)
        self.i5Value.setObjectName("i5Value")
        self.gridLayout.addWidget(self.i5Value, 9, 3, 1, 1)
        self.i6Value = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i6Value.sizePolicy().hasHeightForWidth())
        self.i6Value.setSizePolicy(sizePolicy)
        self.i6Value.setAlignment(QtCore.Qt.AlignCenter)
        self.i6Value.setObjectName("i6Value")
        self.gridLayout.addWidget(self.i6Value, 10, 3, 1, 1)
        self.layoutWidget4 = QtGui.QWidget(self.tab_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 0, 691, 56))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_21 = QtGui.QLabel(self.layoutWidget4)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setWordWrap(False)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_3.addWidget(self.label_21)
        self.r0box = QtGui.QDoubleSpinBox(self.layoutWidget4)
        self.r0box.setDecimals(3)
        self.r0box.setMaximum(200.0)
        self.r0box.setSingleStep(0.001)
        self.r0box.setProperty("value", 100.0)
        self.r0box.setObjectName("r0box")
        self.horizontalLayout_3.addWidget(self.r0box)
        self.label_22 = QtGui.QLabel(self.layoutWidget4)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_3.addWidget(self.label_22)
        self.r100box = QtGui.QDoubleSpinBox(self.layoutWidget4)
        self.r100box.setDecimals(3)
        self.r100box.setMaximum(200.0)
        self.r100box.setSingleStep(0.001)
        self.r100box.setProperty("value", 138.509)
        self.r100box.setObjectName("r100box")
        self.horizontalLayout_3.addWidget(self.r100box)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.PrintButton = QtGui.QPushButton(TempForm)
        self.PrintButton.setObjectName("PrintButton")
        self.verticalLayout.addWidget(self.PrintButton)

        self.retranslateUi(TempForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TempForm)
        TempForm.setTabOrder(self.NameBox, self.SerialEdit)
        TempForm.setTabOrder(self.SerialEdit, self.SerialEdit_2)
        TempForm.setTabOrder(self.SerialEdit_2, self.OwnerBox)
        TempForm.setTabOrder(self.OwnerBox, self.INNEdit)
        TempForm.setTabOrder(self.INNEdit, self.minBox)
        TempForm.setTabOrder(self.minBox, self.maxBox)
        TempForm.setTabOrder(self.maxBox, self.pminBox)
        TempForm.setTabOrder(self.pminBox, self.pmaxBox)
        TempForm.setTabOrder(self.pmaxBox, self.KleimoEdit)
        TempForm.setTabOrder(self.KleimoEdit, self.tvos_box)
        TempForm.setTabOrder(self.tvos_box, self.water_box)
        TempForm.setTabOrder(self.water_box, self.atmkpa_box)
        TempForm.setTabOrder(self.atmkpa_box, self.atmmm_box)
        TempForm.setTabOrder(self.atmmm_box, self.PoverBox)
        TempForm.setTabOrder(self.PoverBox, self.dateEdit)
        TempForm.setTabOrder(self.dateEdit, self.DayBox)
        TempForm.setTabOrder(self.DayBox, self.MonthBox)
        TempForm.setTabOrder(self.MonthBox, self.tabWidget)
        TempForm.setTabOrder(self.tabWidget, self.r0box)
        TempForm.setTabOrder(self.r0box, self.r100box)
        TempForm.setTabOrder(self.r100box, self.t1)
        TempForm.setTabOrder(self.t1, self.i1)
        TempForm.setTabOrder(self.i1, self.t2)
        TempForm.setTabOrder(self.t2, self.i2)
        TempForm.setTabOrder(self.i2, self.t3)
        TempForm.setTabOrder(self.t3, self.i3)
        TempForm.setTabOrder(self.i3, self.t4)
        TempForm.setTabOrder(self.t4, self.i4)
        TempForm.setTabOrder(self.i4, self.t5)
        TempForm.setTabOrder(self.t5, self.i5)
        TempForm.setTabOrder(self.i5, self.t6)
        TempForm.setTabOrder(self.t6, self.i6)
        TempForm.setTabOrder(self.i6, self.PrintButton)

    def retranslateUi(self, TempForm):
        TempForm.setWindowTitle(QtGui.QApplication.translate("TempForm", "Поверка датчика температуры", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("TempForm", "Диапазон поверки", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("TempForm", "Пределы измерения датчика", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("TempForm", "Номер клейма предыдущей поверки", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("TempForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">темп. воздуха (20±5), °C</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("TempForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">влажность (50÷80), %</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("TempForm", "атм. давление", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("TempForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">97,3÷105,3 кПа</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("TempForm", "730÷790 мм.рт.ст", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("TempForm", "Поверитель", None, QtGui.QApplication.UnicodeUTF8))
        self.PoverBox.setItemText(0, QtGui.QApplication.translate("TempForm", "О. П. Голуб", None, QtGui.QApplication.UnicodeUTF8))
        self.PoverBox.setItemText(1, QtGui.QApplication.translate("TempForm", "Е. В. Денис", None, QtGui.QApplication.UnicodeUTF8))
        self.PoverBox.setItemText(2, QtGui.QApplication.translate("TempForm", "Н. В. Григорьева", None, QtGui.QApplication.UnicodeUTF8))
        self.PoverBox.setItemText(3, QtGui.QApplication.translate("TempForm", "С. В. Багаева", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("TempForm", "Дата", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("TempForm", "Печатать:", None, QtGui.QApplication.UnicodeUTF8))
        self.DayBox.setText(QtGui.QApplication.translate("TempForm", "день", None, QtGui.QApplication.UnicodeUTF8))
        self.MonthBox.setText(QtGui.QApplication.translate("TempForm", "месяц", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("TempForm", "Тип", None, QtGui.QApplication.UnicodeUTF8))
        self.NameBox.setItemText(0, QtGui.QApplication.translate("TempForm", "644", None, QtGui.QApplication.UnicodeUTF8))
        self.NameBox.setItemText(1, QtGui.QApplication.translate("TempForm", "244", None, QtGui.QApplication.UnicodeUTF8))
        self.NameBox.setItemText(2, QtGui.QApplication.translate("TempForm", "3144", None, QtGui.QApplication.UnicodeUTF8))
        self.NameBox.setItemText(3, QtGui.QApplication.translate("TempForm", "248", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("TempForm", "Заводской номер ИП", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("TempForm", "Заводской номер ТСП", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("TempForm", "Принадлежит", None, QtGui.QApplication.UnicodeUTF8))
        self.OwnerBox.setItemText(0, QtGui.QApplication.translate("TempForm", "ОАО \"СН-МНГ\"", None, QtGui.QApplication.UnicodeUTF8))
        self.OwnerBox.setItemText(1, QtGui.QApplication.translate("TempForm", "ОАО \"ТНК-Нижневартовск\"", None, QtGui.QApplication.UnicodeUTF8))
        self.OwnerBox.setItemText(2, QtGui.QApplication.translate("TempForm", "ОАО \"СНГДУ-2\"", None, QtGui.QApplication.UnicodeUTF8))
        self.OwnerBox.setItemText(3, QtGui.QApplication.translate("TempForm", "ОАО \"СНГ\"", None, QtGui.QApplication.UnicodeUTF8))
        self.OwnerBox.setItemText(4, QtGui.QApplication.translate("TempForm", "ОАО \"ННП\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("TempForm", "ИНН", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("TempForm", "Верхний предел", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("TempForm", "Нижний предел", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("TempForm", "Верхний предел", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("TempForm", "Нижний предел", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("TempForm", "Датчик и протокол", None, QtGui.QApplication.UnicodeUTF8))
        self.p1Value.setText(QtGui.QApplication.translate("TempForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.p2Value.setText(QtGui.QApplication.translate("TempForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.p3Value.setText(QtGui.QApplication.translate("TempForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.p4Value.setText(QtGui.QApplication.translate("TempForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.p5Value.setText(QtGui.QApplication.translate("TempForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.p6Value.setText(QtGui.QApplication.translate("TempForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("TempForm", "Измеренная температура", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("TempForm", "Действительная температура", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("TempForm", "Заданная температура", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("TempForm", "измереннный ток", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("TempForm", "Погрешность", None, QtGui.QApplication.UnicodeUTF8))
        self.i1Value.setText(QtGui.QApplication.translate("TempForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.i2Value.setText(QtGui.QApplication.translate("TempForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.i3Value.setText(QtGui.QApplication.translate("TempForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.i4Value.setText(QtGui.QApplication.translate("TempForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.i5Value.setText(QtGui.QApplication.translate("TempForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.i6Value.setText(QtGui.QApplication.translate("TempForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("TempForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">R0</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(99,941<span style=\" font-family:\'DejaVu Sans, sans-serif\';\">÷100,059) Ом</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("TempForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">R 100</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(138,373<span style=\" font-family:\'DejaVu Sans, sans-serif\';\">÷138,639) Ом</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("TempForm", "Измерения", None, QtGui.QApplication.UnicodeUTF8))
        self.PrintButton.setText(QtGui.QApplication.translate("TempForm", "Протокол...", None, QtGui.QApplication.UnicodeUTF8))

